import {
  BadgeCheck,
  Building2,
  CalendarClock,
  ChartSpline,
  Clock3,
  DatabaseZap,
  GitBranch,
  GraduationCap,
  Handshake,
  Headphones,
  MessagesSquare,
  Presentation,
  Send,
  ShoppingBag,
  Store,
  UserRoundX,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  BadgeCheck,
  Building2,
  CalendarClock,
  ChartSpline,
  Clock3,
  DatabaseZap,
  GitBranch,
  GraduationCap,
  Handshake,
  Headphones,
  MessagesSquare,
  Presentation,
  Send,
  ShoppingBag,
  Store,
  UserRoundX,
  Workflow,
  Wrench,
  Zap,
};
